services:
  gateway:
    build: ./gateway
    ports:
      - '3000:3000'
    env_file:
      - ./gateway/.env
    depends_on:
      - auth
      - event

  auth:
    build: ./auth
    ports:
      - '3001:3001'
    env_file:
      - ./auth/.env
    depends_on:
      - mongo

  event:
    build: ./event
    ports:
      - '3002:3002'
    env_file:
      - ./event/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./mongo/data:/data/db
